### ISSUE TITLE
Rewards emission change

### ISSUE THREAD

**Issue by QGarchery** [morpho-org/morpho-aave-v3#821]
When the emission of rewards changes, nothing happens from Morpho's side. This could be an issue if it increases because users would receive more of their share of what the Morpho contract will receive from Aave. This issue is due to the fact that the accrual on Morpho takes the last emission rate, and it could apply it to a position since the previous update of Morpho (that may be before the change of the emission rate). It may not be a big issue in terms of quantity, and potentially not even noticeable.

One more worrying issue is if the emission is set to 0, but the rewards manager is also activated on Morpho's side. As soon as emission is set to non-zero, users would be able to claim rewards as if it was non-zero since the last update on Morpho

**Comment by MerlinEgalite** [comment]
I think this is more the opposite ie there's no real issue if the rewards `emissionPerSecond` is decreased but there is one when it's increased.

In your example, when setting `emissionPerSecond` to 0, the index won't be updated because of this line:
https://github.com/morpho-org/morpho-aave-v3/blob/4c3f4fb7743866e87f66220f5676f9f6740c1b9f/src/RewardsManager.sol#L469
So user's rewards would be underestimated.

In the case when it's increased, the number of rewards will be slightly higher than what it should, overestimating user's rewards. This could cause some reverts.

**Comment by MerlinEgalite** [comment]
Ok sorry I mis-read your message

**Comment by MathisGD** [comment]
I validate the issue too. I'm wondering why we are not using the "user index" of Morpho on Aave instead, which would completely remove the need for reading "emission per second" thus resolving the issue. 

NB: this makes me think about the issue that we had in morpho-v1 when we were using the pools rates to compute Morpho's indexes (it turned out using indexes only seems to be good idea).

**Comment by pakim249CAL** [comment]
> I validate the issue too. I'm wondering why we are not using the "user index" of Morpho on Aave instead, which would completely remove the need for reading "emission per second" thus resolving the issue.
> 
> NB: this makes me think about the issue that we had in morpho-v1 when we were using the pools rates to compute Morpho's indexes (it turned out using indexes only seems to be good idea).

I tried implementing your suggestion and ran into difficulties. We need an asset index that can be virtually updated for use in view functions in our rewards manager, and this doesn't seem very practical using the user asset index as aave does not include a getter to do this. I tried a few other solutions, and they just break everything ...so 🤷 . I'm still looking into it.

One thing I'm realizing is that we could have probably separated the rewards logic completely from Morpho. The relationship between the rewards manager and morpho are much tighter than they need to be. We could have gone with an architecture where morpho approves the rewards manager to claim rewards on behalf of morpho, and all rewards could be transferred from the rewards manager contract instead. This would reduce risk in Morpho, as Morpho transferring tokens out that it does not actually account for in its own storage seems like a not great design choice.

**Comment by MerlinEgalite** [comment]
Yes but how do you the accounting? Else you can just to use a merkle tree

**Comment by QGarchery** [comment]
The only reason that the rewards manager is tightly integrated is to do the accounting as @MerlinEgalite said. For example when someone supplies we have to update their accrued rewards considering the supply they had just before. 

Is it possible to always update the rewards index in AaveV3 ? That would be more costly but it would also simplify the accounting greatly

**Comment by makcandrov** [comment]
Can't we invert [these two lines](https://github.com/morpho-org/morpho-aave-v3/blob/03cee70c50a8d0abf3c5eebdd416127fe8a54ea5/src/Morpho.sol#L271-L272) so that Morpho can claim rewards on Aave before doing the accounting on our side? This way, all the indexes will be up to date on Aave. We can then retrieve them using the function [`getRewardsData`](https://github.com/aave/aave-v3-periphery/blob/1fdd23b38cc5b6c095687b3c635c4d761ff75c4c/contracts/rewards/RewardsDistributor.sol#L45).

**Comment by MerlinEgalite** [comment]
Does it change something (except it's a gas opti)?

**Comment by makcandrov** [comment]
My bad I deleted my comment, it didn't solve the issue

**Comment by MerlinEgalite** [comment]
Don't delete because I answered you can just put an EDIT so we have trace of what we said (perhaps it's not that dumb)

**Comment by MerlinEgalite** [comment]
After rechecking during a discussion with @MathisGD I'm not sure that there's an issue, else, it's not clear to me anymore. 

In the current implementation: https://github.com/morpho-org/morpho-aave-v3/blob/affa6a6271e60fd7c3e248b0602973730557c83e/src/RewardsManager.sol#L460-L461

The last index on the pool is queried which has taken into account the change of the speed (if any). Then we compute the new rewards index based on the previous rewards index on the pool (and not the one stored locally in the `RewardsManager`) and the current speed used since the last update.

https://github.com/morpho-org/morpho-aave-v3/blob/affa6a6271e60fd7c3e248b0602973730557c83e/src/RewardsManager.sol#L463-L473

I remember doing this because of supposed gas optimizations (which I don't think is worth at all after thinking about it).

**Comment by makcandrov** [comment]
You seem to be right. In my opinion, the main argument is that when Aave updates the emission per second, they also update the index ([here](https://github.com/aave/aave-v3-periphery/blob/1fdd23b38cc5b6c095687b3c635c4d761ff75c4c/contracts/rewards/RewardsDistributor.sol#L207-L211)). If they didn't update the index, the issue would remain.

Don't we have a test that verifies that there is no problem, just to be sure?

**Comment by Rubilmax** [comment]
> Don't we have a test that verifies that there is no problem, just to be sure?

Working on it and will link this issue

**Comment by MathisGD** [comment]
I'm still in favor of using only indexes and never using the emission speed, as it is generally more robust (and would be cleaner in our case).

**Comment by MerlinEgalite** [comment]
> I'm still in favor of using only indexes and never using the emission speed, as it is generally more robust (and would be cleaner in our case).

Querying the index on the pool will still use the emission speed under the wood

**Comment by MerlinEgalite** [comment]
Nullifying this issue then

**Comment by Rubilmax** [comment]
Closed as completed because we've added the test ^^
